// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330061047_HabitacionesUpdate")]
    partial class HabitacionesUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Habitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoHabitacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumHabitacion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Piso")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoCama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoHabitacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Habitaciones", (string)null);
                });

            modelBuilder.Entity("backend.Models.Huesped", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("Huespedes", (string)null);
                });

            modelBuilder.Entity("backend.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Mora")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("backend.Models.Huesped", b =>
                {
                    b.HasOne("backend.Models.Reserva", "Reserva")
                        .WithMany("Huespedes")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("backend.Models.Reserva", b =>
                {
                    b.HasOne("backend.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("backend.Models.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("backend.Models.Reserva", b =>
                {
                    b.Navigation("Huespedes");
                });
#pragma warning restore 612, 618
        }
    }
}
