// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330183424_FechasReservas")]
    partial class FechasReservas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HuespedReserva", b =>
                {
                    b.Property<Guid>("HuespedesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservasId")
                        .HasColumnType("uuid");

                    b.HasKey("HuespedesId", "ReservasId");

                    b.HasIndex("ReservasId");

                    b.ToTable("Huespes_Reservas", (string)null);
                });

            modelBuilder.Entity("backend.Models.Habitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacidadPersonas")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoHabitacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumHabitacion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Piso")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<string>("TipoCama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoHabitacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Habitaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CapacidadPersonas = 2,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "001",
                            Piso = 1,
                            Precio = 150m,
                            TipoCama = "INDIVIDUAL",
                            TipoHabitacion = "SIMPLE"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CapacidadPersonas = 3,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "003",
                            Piso = 1,
                            Precio = 200m,
                            TipoCama = "INDIVIDUAL",
                            TipoHabitacion = "DOBLE_INDIVIDUAL"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CapacidadPersonas = 2,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "004",
                            Piso = 1,
                            Precio = 160m,
                            TipoCama = "INDIVIDUAL",
                            TipoHabitacion = "SIMPLE"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CapacidadPersonas = 4,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "005",
                            Piso = 1,
                            Precio = 300m,
                            TipoCama = "MATRIMONIAL",
                            TipoHabitacion = "SUITE"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CapacidadPersonas = 2,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "006",
                            Piso = 1,
                            Precio = 180m,
                            TipoCama = "INDIVIDUAL",
                            TipoHabitacion = "SIMPLE"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CapacidadPersonas = 3,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "007",
                            Piso = 2,
                            Precio = 220m,
                            TipoCama = "INDIVIDUAL",
                            TipoHabitacion = "DOBLE_INDIVIDUAL"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CapacidadPersonas = 2,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "008",
                            Piso = 2,
                            Precio = 250m,
                            TipoCama = "MATRIMONIAL",
                            TipoHabitacion = "DOBLE_MATRIMONIAL"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CapacidadPersonas = 4,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "009",
                            Piso = 2,
                            Precio = 350m,
                            TipoCama = "MATRIMONIAL",
                            TipoHabitacion = "SUITE"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CapacidadPersonas = 2,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "010",
                            Piso = 3,
                            Precio = 190m,
                            TipoCama = "INDIVIDUAL",
                            TipoHabitacion = "SIMPLE"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CapacidadPersonas = 3,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "011",
                            Piso = 3,
                            Precio = 230m,
                            TipoCama = "INDIVIDUAL",
                            TipoHabitacion = "DOBLE_INDIVIDUAL"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CapacidadPersonas = 2,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "012",
                            Piso = 3,
                            Precio = 260m,
                            TipoCama = "MATRIMONIAL",
                            TipoHabitacion = "DOBLE_MATRIMONIAL"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CapacidadPersonas = 5,
                            EstadoHabitacion = "LIBRE",
                            NumHabitacion = "013",
                            Piso = 3,
                            Precio = 400m,
                            TipoCama = "MATRIMONIAL",
                            TipoHabitacion = "DOBLE_MATRIMONIAL"
                        });
                });

            modelBuilder.Entity("backend.Models.Huesped", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Genero")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Huespedes", (string)null);
                });

            modelBuilder.Entity("backend.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCheckInActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCheckInEsperado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCheckOutActual")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCheckOutEsperado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HabitacionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Mora")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("HuespedReserva", b =>
                {
                    b.HasOne("backend.Models.Huesped", null)
                        .WithMany()
                        .HasForeignKey("HuespedesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Reserva", null)
                        .WithMany()
                        .HasForeignKey("ReservasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Reserva", b =>
                {
                    b.HasOne("backend.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("backend.Models.Habitacion", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
